NXT-16477: Fix for isomorphic build for TabLayout/RefocusDecorator (#396)
### Checklist

* [x] I have read and understand the [contribution
guide](https://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG
entry](https://enactjs.com/docs/developer-guide/contributing/changelogs/)
is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull
request)
enact pack --production --isomorphic --locales=tv with sample of
tablayout
results in uild error with 

`Unable to generate prerender of app state HTML for af-ZA:
ReferenceError: window is not defined`


### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added typeof window in TabLayout/RefocusDecorator

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)


### Links
[//]: # (Related issues, references)
NXT-16477

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian
([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))